{% set version = "0.2.3" %}

package:
  name: qhub-dask
  version: {{ version }}

build:
  number: 0
  noarch: generic

requirements:
  run:
    - dask ==2.14.0
    - distributed ==2.14
    - dask-gateway ==0.6.1
    - bokeh==2.2.3

test:
  imports:
    - dask

about:
  home: https://github.com/quansight/qhub
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Qhub dask dependencies"

extra:
  recipe-maintainers:
    - prasunanand
    - costrouc
    - viniciusdc
