{% set version = "0.4.0" %}

package:
  name: qhub-dask
  version: {{ version }}

build:
  number: 0
  noarch: generic

requirements:
  run:
    - dask ==2021.7.2
    - distributed ==2021.7.2
    - dask-gateway ==0.9.0

test:
  imports:
    - dask

about:
  home: https://github.com/quansight/qhub
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Qhub dask dependencies"

extra:
  recipe-maintainers:
    - prasunanand
    - costrouc
    - viniciusdc
    - iameskild
